name: Deploy Next.js to Azure using Docker

on:
  push:
    branches:
      - main
      - secondary-test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: prismaprimeinvestregistry.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t prismaprimeinvestregistry.azurecr.io/ppi-web:latest .

      - name: Push Docker image to ACR
        run: |
          docker push prismaprimeinvestregistry.azurecr.io/ppi-web:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: prisma-prime-invest
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Usando o Publish Profile
          images: prismaprimeinvestregistry.azurecr.io/ppi-web:latest
