name: Deploy Next.js to Azure using Docker

on:
  push:
    branches:
      - main
      - secondary-test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Login no Azure Container Registry (ACR) ou Docker Hub
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: prismaprimeinvestregistry.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # 3. Build da imagem Docker
      - name: Build Docker image
        run: |
          docker build -t prismaprimeinvestregistry.azurecr.io/ppi-web:latest .

      # 4. Push da imagem para o Azure Container Registry
      - name: Push Docker image to ACR
        run: |
          docker push prismaprimeinvestregistry.azurecr.io/ppi-web:latest

      # 5. Deploy no Azure Web App com Docker
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "prisma-prime-invest"
          images: "prismaprimeinvestregistry.azurecr.io/ppi-web:latest"
